SLEEP_TIME_BATTERY = 30
SLEEP_TIME_ELECTION_FIRST = 60
SLEEP_TIME_ELECTION_MAX = 90
SLEEP_TIME_ELECTION_MIN = 30
SLEEP_TIME_ELECTION_RESULTS = 30
SLEEP_TIME_ENGINE = 5
SLEEP_TIME_SENSORS = 15
SLEEP_TIME_HEARTBEAT = 15
